### ISSUE TITLE
Moderation Improvements

### ISSUE THREAD

**Issue by pixeldesu** [Retrospring/retrospring#10]
## Moderation Power

Since all moderators have the same power all time, once we grew bigger, this could lead to abuse of being able to ban people (of course, if we knew that, we'd remove all these bad people), but there should be some Power Level for moderators, which first just allows them to report, vote and discuss, and after time (or after an admin set it) allows them to ban people etc.
## Moderation Blame

Associate the executing moderator with the banned user or deleted content for better control and tracking of moderators.

**Comment by neptuwunium** [comment]
Pagination would be nice too.

**Comment by pixeldesu** [comment]
Closing this as we technically solved/improved (self-)moderation with implementing other things.
