### ISSUE TITLE
Remove connection to a social service if the token expired

### ISSUE THREAD

**Issue by nilsding** [Retrospring/retrospring#123]
Every now and then I see errors like `Twitter::Error::Unauthorized: Invalid or expired token` whenever someone answers a question.

It would be nice to respond to unauthorised errors with the disconnection of a service.  Ideally the user should be informed about that, preferably not via a question (related: #78).

**Comment by pixeldesu** [comment]
Technically, we can introduce a notification type for service disconnects in cases of errors and tell a user to reconnect.

That said, I checked Sentry and I don't even see a `Twitter::Error::Unauthorized` anymore, so this hasn't happened in quite a while.
