### ISSUE TITLE
User actions on following/followers list get cut off

### ISSUE THREAD

**Issue by raccube** [Retrospring/retrospring#126]
![image](https://user-images.githubusercontent.com/6197148/83312684-265a1800-a20b-11ea-8d3b-5eb7d5708eb8.png)

Reported by @coderobe

**Comment by pixeldesu** [comment]
If someone wants a quick-win, it's literally solved by removing this line:
https://github.com/Retrospring/retrospring/blob/master/app/assets/stylesheets/components/_userbox.scss#L2
