### ISSUE TITLE
Newlines are stripped from plain text

### ISSUE THREAD

**Issue by coderobe** [Retrospring/retrospring#129]
Any sort of line break appears to get stripped from questions and answers. Is this intentional? Is this using some other inline formatting a la markdown?

It would be nice to have intentional line breaks in question/ answer bodies, couldn't figure out how to reliably make that happen.

**Comment by nilsding** [comment]
The formatting _is_ Markdown.

**Comment by raccube** [comment]
Just need to add an extra line break. Although I do think this isn't exactly intuitive, hence why #26 was proposed.

**Comment by coderobe** [comment]
![image](https://user-images.githubusercontent.com/8442384/83328989-1c75fa80-a287-11ea-8833-1408de22e5ae.png)
![image](https://user-images.githubusercontent.com/8442384/83329000-27308f80-a287-11ea-8f5f-f692bafb1d5e.png)
**is it?**

**Comment by raccube** [comment]
No Markdown in questions, only in answers.

**Comment by nilsding** [comment]
Questions are not formatted.

**Comment by coderobe** [comment]
I see.
UX >.>
![image](https://user-images.githubusercontent.com/8442384/83329113-cd7c9500-a287-11ea-8d37-8db7dd593b90.png)

**Comment by pixeldesu** [comment]
We'll try to make formatting options in places more obvious implementing #28 at some point.

**Comment by pixeldesu** [comment]
As said, we already have another issue for adding formatting help and now with the recent link additions, adding paragraphs to questions also works now!
