### ISSUE TITLE
Inform user why enabling push notifications doesn't work

### ISSUE THREAD

**Issue by Craftplacer** [Retrospring/retrospring#1369]
### Pitch

The website does nothing when clicking the button and it fails. It would be helpful informing what has failed or remind them to check if they're blocking something(?)

### Motivation

EasyList's Notifications sublist is blocking the endpoint for enabling web push.

**Comment by pixeldesu** [comment]
I checked the code and this actually seems more like a bug than a specific feature request, since we do actually (try to) catch errors and display a notification. 

But maybe the way the promises are nested inside there causes that to go missing.
