### ISSUE TITLE
Use sane date format for specifying ban duration

### ISSUE THREAD

**Issue by nilsding** [Retrospring/retrospring#140]
Right now it uses `%m/%d/%Y %I:%M %p`, which shouldn't even be a thing.  Use ISO 8601 date format instead.

Maybe also try out how `Time.parse` from `require "time"` parses certain strings -- perhaps we don't need a specific format then.

https://github.com/Retrospring/retrospring/blob/5ae5ed6c8dd6f1b150f19543574a63069f46313a/app/controllers/ajax/moderation_controller.rb#L118

**Comment by raccube** [comment]
Maybe we could just specify duration instead?

**Comment by pixeldesu** [comment]
The main issue behind this is not the format of the date itself, but that it at the moment is required to be put in manually, which is resolved with #109
