### ISSUE TITLE
URLs in notifications sometimes break

### ISSUE THREAD

**Issue by coderobe** [Retrospring/retrospring#141]
![image](https://user-images.githubusercontent.com/8442384/84259938-827d4000-ab19-11ea-8772-7789f499d5f6.png)
(links to '`https://i.imgur.com/zYmZel%5B...%5D`', the [...] gets rendered into the href and the URL is cut off)

When an URL is present in a question or answer, and the answer text gets cut off in the notification due to its length, the URL is still clickable, but leads to an incomplete or straight up broken target href.

**Comment by pixeldesu** [comment]
I'll add a note about this in #99 because it's also happening because of the text shortening.
