### ISSUE TITLE
Title on "View all questions from this user" page is not translated

### ISSUE THREAD

**Issue by pixeldesu** [Retrospring/retrospring#1423]
### Steps to reproduce the problem

1. Be an admin/a moderator on Retrospring
2. On a anonymous question, click "Show all questions from this user" in the actions dropdown

### Expected behaviour

The title of the page displays properly.

### Actual behaviour

The title of the page shows the HTML tag for a missing translation.

### Specifications

Retrospring 2023.1019.0

**Comment by chahmedejaz** [comment]
Hey @pixeldesu - I'd love to work on this issue, can you please assign it to me? Thanks. :)

**Comment by pixeldesu** [comment]
@chahmedejaz Done!
