### ISSUE TITLE
The delete button on inbox items stays disabled after cancelling the deletion operation

### ISSUE THREAD

**Issue by pixeldesu** [Retrospring/retrospring#1427]
### Steps to reproduce the problem

1. Go to your inbox
2. On an inbox entry, press "Delete"
3. Press "Cancel"

### Expected behaviour

The "Delete" button is clickable again.

### Actual behaviour

The "Delete" button stays disabled.

### Specifications

Retrospring 2023.1028.1

**Comment by milinddethe15** [comment]
Hi, I want to work on this. Assign me.

**Comment by chahmedejaz** [comment]
Hey @pixeldesu  - I'd love to work on this issue. Can you please assign it to me? Thanks.
