### ISSUE TITLE
Duplicate Post Prevention

### ISSUE THREAD

**Issue by raccube** [Retrospring/retrospring#144]
I've seen quite a few duplicate questions and answers get posted lately. 
![image](https://user-images.githubusercontent.com/6197148/87873790-3d6fe780-c9bc-11ea-8b8d-89184c3b5f47.png)

We should implement something on the backend for when a question or answer gets posted with the duplicate content.

Twitter actually deals with it in this way, returning a "You already tweeted that." error message if you try to post a tweet with repeat content.

**Comment by pixeldesu** [comment]
It's probably a frontend issue, I expect the users are clicking the submit buttons thrice or more often and that causes the question to be answered multiple times.

But of course, preventing that in the backend is also good.

In general, a user should only able to be answer a question once anyway.
