### ISSUE TITLE
Add Missing Step in the Development Setup Wiki 

### ISSUE THREAD

**Issue by chahmedejaz** [Retrospring/retrospring#1445]
### Pitch

- It's observed that following are some missing steps in the [Development Setup Wiki](https://github.com/Retrospring/retrospring/wiki/Setup#development-1):
  - In [Initialize Database](https://github.com/Retrospring/retrospring/wiki/Setup#initialize-database), we need to create the database first before running the migrations.
    - We can replace this step with `bundle exec rake db:prepare RAILS_ENV=development` 
    - The above command will create, migrate, and seed the database
- We also need to build Rails assets in development as well.

### Motivation

It will improve the setup wiki

**Comment by pixeldesu** [comment]
I made the relevant suggestions to the Setup wiki page, thank you!
