### ISSUE TITLE
Add "Copy to clipboard" sharing option to answers

### ISSUE THREAD

**Issue by pixeldesu** [Retrospring/retrospring#1448]
_Originally referenced from: https://github.com/Retrospring/retrospring/issues/1083#issuecomment-1793472828_

### Pitch

Add the ability to copy the "question - answer [link]" text into the clipboard after answering a question.

### Motivation

This adds the ability to quickly post the sharing text to platforms that don't have support for URL-based sharing intents (like Twitter, Tumblr, etc.)

**Comment by chahmedejaz** [comment]
I'm working on this issue.
