### ISSUE TITLE
You can send yourself questions

### ISSUE THREAD

**Issue by LunarLambda** [Retrospring/retrospring#151]
Is this intentional? It's pretty silly

(The person asking the question is myself.)
![image](https://user-images.githubusercontent.com/38919842/97612871-3c694000-1a18-11eb-9e2a-55016a5a7b69.png)

**Comment by pixeldesu** [comment]
It's intentional! Not really of use to ask yourself any question, but on the other hand, also doesn't do much harm.

I don't even remember our thought process behind leaving that in anymore 🤔
