### ISSUE TITLE
Entities can be smiled multiple times

### ISSUE THREAD

**Issue by pixeldesu** [Retrospring/retrospring#1517]
### Steps to reproduce the problem

* Have super slow internet.
* Click rapidly on the smile button on an answer or comment.

### Expected behaviour

There is either one or no smile from myself.

### Actual behaviour

There are many smiles by myself.

### Proposed solution(s)

* Add model validation that only allows one reaction per user
* Disable the button after it has been clicked via JS (add a simple Stimulus controller for this)

### Specifications

Retrospring 2023.1217.0

**Comment by nilsding** [comment]
new repro:

- smile an answer
- reload the page
- smile it again

unless you just smiled an answer it's impossible to unsmile it again

**Comment by raccube** [comment]
A database constraint has been added in order to deal with this.
