### ISSUE TITLE
Inbox can't be opened.

### ISSUE THREAD

**Issue by heartkith** [Retrospring/retrospring#1579]
### Steps to reproduce the problem

1. Refresh the page.
2. Logged in to the account with another device.
3. Using another browser to open Retrospring 
...

### Expected behaviour

The Inbox feature can be opened and will show the questions I received from anyone.

### Actual behaviour

Everytime I clicked the Inbox page, it always shows an internal error and won't show any questions that I got.

### Detailed description

It's been around a weeks since the Inbox feature on my account can't be opened and it's always shows there's an internal error while other users can see their Inbox normally. I already changed the browser and logged out from the account to do another login but still won't show any questions.

### Specifications

Latest version of Retrospring, Google Chrome 120.

**Comment by pixeldesu** [comment]
@heartkith I fixed this issue yesterday, is it still occuring to you?
