### ISSUE TITLE
Internal Server Error

### ISSUE THREAD

**Issue by inhahe** [Retrospring/retrospring#1673]
### Steps to reproduce the problem

I attempted to smile this post: https://retrospring.net/@Dogboy2709/a/112090193238316757. I may have had already smiled it, I'm not sure. I probably had. I got

```
500 Internal Server Error
If this page shows up, something went wrong. We've dispatched our army of raccoons to fix it.

We get notified about issues, but feel free to contact us:

[Mastodon: @retrospring@floss.social](https://floss.social/@retrospring)  [Twitter: @Retrospring](https://twitter.com/Retrospring)  [GitHub](https://github.com/Retrospring/retrospring)
[Back](javascript:history.back())  [Home](https://retrospring.net/) 
```

I tried three times and got the same result each time.

### Expected behaviour

If I already smiled it, the happy face should have changed colors to unsmiled and the smile count should have decreased by one. Otherwise, it should have changed color to smiled and the smile count should have increased by one. (I forget for sure which color is which.)

### Actual behaviour

Internal Server Error

### Detailed description

See above.

### Specifications

I attempted to smile this post: https://retrospring.net/@Dogboy2709/a/112090193238316757. I may have had already smiled it, I'm not sure. I probably had. I got

```
500 Internal Server Error
If this page shows up, something went wrong. We've dispatched our army of raccoons to fix it.

We get notified about issues, but feel free to contact us:

[Mastodon: @retrospring@floss.social](https://floss.social/@retrospring)  [Twitter: @Retrospring](https://twitter.com/Retrospring)  [GitHub](https://github.com/Retrospring/retrospring)
[Back](javascript:history.back())  [Home](https://retrospring.net/) 
```

I tried three times and got the same result each time.

**Comment by inhahe** [comment]
I also just tried on this post here https://retrospring.net/@fizzyarthur/a/112090274684482981 (another answer to the same question, and another one that I may have already smiled) and got the same result (500).

**Comment by fizzyarthur** [comment]
I've successfully reproduced this issue using Firefox 123 running on Kubuntu 23.10.

**Comment by pixeldesu** [comment]
I can confirm the issue myself as well, I'm already thinking about possible solutions. 

I could fix the 500 Internal Server error from appearing, but that doesn't solve the issue with the button showing the wrong state, and my current approach would require a massive refactoring in the area to fix that completely.

**Comment by inhahe** [comment]
I don't understand why you'd have to do massive refactoring when unsmiling *used to* work? It seems it must be something small that someone broke with an update (or even something big, but still something you could simply revert), or an error in the database?

**Comment by pixeldesu** [comment]
For reference, this didn't work for ages now, I can probably even pinpoint that it must have been several months.

It happened with a refactoring in regards to database queries if something is smiled or not, in combination with a refactoring that I did with how smiling works in general.

I think I found out what causes the issue and can investigate again later.
