### ISSUE TITLE
Beta Mode/Restricted Access

### ISSUE THREAD

**Issue by pixeldesu** [Retrospring/retrospring#17]
_"OH MY GOD RETROSPRING WILL GET CLOSED DOWN AGAIN."_

As a preparation to get the development/pre-test/beta session of Retrospring running, we need a way to stop people from being able to register on the site just like that.

The easiest way to do this would be adding a section to the config to enable this mode and appending a list with the allowed mail addresses to it.

**Comment by neptuwunium** [comment]
Or with invitations as per #7

**Comment by pixeldesu** [comment]
As we pretty much don't have an "early access testing" commitment anymore, I don't think that feature is particularly interesting nor necessary.
