### ISSUE TITLE
Page going completely black after changing theme

### ISSUE THREAD

**Issue by cannibalcreature** [Retrospring/retrospring#1777]
### Steps to reproduce the problem

1. Went into the settings to change theme
2. Changed some of the background and text colors and hit save
3. Went back into the settings to change a couple more couples, specifically the one that changes the boxes.
4. When I hit save and viewed my profile, it was completely black and all I can see is my icon but I can’t navigate the site at all.

### Expected behaviour

It should have changed my theme to the color I selected.

### Actual behaviour

It blacked out my entire profile.

### Detailed description

If possible, I would really just like to just have my theme reset completely. Username is the same here!

### Specifications

using Safari on an iPhone 15

**Comment by cannibalcreature** [comment]
![IMG_4809](https://github.com/Retrospring/retrospring/assets/174126339/70e847f1-1423-41df-b957-20c676370876)

**Comment by pixeldesu** [comment]
Removed your theme!
