### ISSUE TITLE
Account History

### ISSUE THREAD

**Issue by pixeldesu** [Retrospring/retrospring#19]
Something more moderation-specific.

How about a account history, which is viewable by each user for themselves, and moderators/admins for each user, this history includes reports (not sure about this one) and deletions of content with the reasoning.

With this, users themselves can see if their account is in a good standing or not and admins/moderators can see how many times they already took action against this user.

This could later on be combined with some sort of "Karma" system removing different abilities from users if they misbehave multiple times.

**Comment by neptuwunium** [comment]
#20
