### ISSUE TITLE
Profile edit history

### ISSUE THREAD

**Issue by raccube** [Retrospring/retrospring#195]
Having an edit history of user profiles would be very useful for moderation.

**Comment by nilsding** [comment]
maybe this helps? https://github.com/paper-trail-gem/paper_trail

**Comment by pixeldesu** [comment]
@nilsding fun coincidence because I actually looked at it for #105 today

**Comment by pixeldesu** [comment]
We intially made this because one moderation case came up where something like this would have been relevant, but the amount of data we'd have to store with all the profiles edits and how rarely it would come to use probably makes this idea a bit overkill.
