### ISSUE TITLE
Unable to reset password - Screen name error

### ISSUE THREAD

**Issue by AMoonRabbit** [Retrospring/retrospring#207]
Hello,

Run into an issue when trying to use the password reset form. There is only a field for email address, and with this field in it tells me that the screen name cannot be blank. My account exists as I can browse publicly to the page. 
![image](https://user-images.githubusercontent.com/3766988/136646685-38bef7fb-ca48-4233-936d-173ce812ce75.png)

**Comment by pixeldesu** [comment]
@raccube didn't we fix that bug at some point? 🤔 (I just remember #77)

**Comment by raccube** [comment]
Yep. Seems to be a regression. Weirdly enough changing the field manually to `user[screen_name]` didn't seemed to submit the form but I didn't get an email.

**Comment by raccube** [comment]
So the configuration for devise doesn't get updated when deployments are made. This is because `config/initializers/devise.rb` contains a secret key. We should move that out of there.

**Comment by AMoonRabbit** [comment]
Nice work, I have successfully reset my password today. Thank you for your help.
