### ISSUE TITLE
Not every language uses "s" to indicate plural (Plural in other languages)

### ISSUE THREAD

**Issue by Centzilius** [Retrospring/retrospring#22]
Some languages (like German) don't use "s" as suffix to indicate plural.
![2015-07-16_12-35-17](https://cloud.githubusercontent.com/assets/1499392/8721031/2ad9bc70-2bb7-11e5-9aa6-852c84dde7b8.png)
![2015-07-16_12-36-50](https://cloud.githubusercontent.com/assets/1499392/8721048/5ae98864-2bb7-11e5-8434-8c294f72fb5c.png)
(The plural of days and months is wrong as well)

**Comment by pixeldesu** [comment]
Already noted in Retrospring/retrospring#3
