### ISSUE TITLE
Hover Widgets

### ISSUE THREAD

**Issue by neptuwunium** [Retrospring/retrospring#25]
The ability to hover over a username and it will show basic info about them, similar to Facebook, and Google+.
- [ ] AJAX Endpoints
- [ ] Main interface
- [ ] JavaScript binding

This will be released in conjunction with #9

**Comment by pixeldesu** [comment]
In general, this is a bit of a large endeavour without a mostly dynamic UI and I'm pretty sure it wouldn't fit too well into the design either. Either making a new issue or reopening if we reconsider this at some point.
