### ISSUE TITLE
Alternate formatting

### ISSUE THREAD

**Issue by neptuwunium** [Retrospring/retrospring#26]
A few users have requested a more "human" formatting, such as I propose;

```
* for bold
_ for underline
- for strikethrough
/ for italic
` for code blocks
> for blockquotes
\ for escape
```

and `<br/>` every newline.

**Comment by pixeldesu** [comment]
Considering we've been rolling with the Markdown subset for years now, changing it now would mean we'd have to support two ways how things are marked up.
