### ISSUE TITLE
Pong should have a AI as enemy

### ISSUE THREAD

**Issue by rugk** [Retrospring/retrospring#264]
The error page pong game is a game against myself. A random entry point for the ball and an AI would be awesome, so I can actually properly play pong and defeat an enemy… :stuck_out_tongue_winking_eye:

**Comment by raccube** [comment]
The pong game got removed as part of #258

**Comment by nilsding** [comment]
The pong game was removed as part of the error page refresh in #258

**Comment by pixeldesu** [comment]
We removed the pong game in #258 solving #220

**Comment by rugk** [comment]
ohhhh okay, saad, and thanks you three, I got it :see_no_evil:
