### ISSUE TITLE
Remove or increase character limit on questions

### ISSUE THREAD

**Issue by angelod1as** [Retrospring/retrospring#276]
I understand the implications of having zero character limit, but at the moment it's too low. I'm receiving stuff spanning two or three questions because of this limit.

That being said, I hope the character limit can be increased (I don't know the current limit, as there's nothing shown there)

**Comment by nilsding** [comment]
The current maximum is 255 characters:

https://github.com/Retrospring/retrospring/blob/bbe5325ba51231b14fd763a751ee92a540a839f4/app/models/question.rb#L8

What do you think would be an acceptable limit?  Maybe 280, like Twitter has it these days?

**Comment by angelod1as** [comment]
In my personal opinion, I'd go way longer, like 600 or so characters. I've got some 2 or 3 part questions but I don't know if this is common with the users.

**Comment by raccube** [comment]
Resolved by #292
