### ISSUE TITLE
Formatting help

### ISSUE THREAD

**Issue by pixeldesu** [Retrospring/retrospring#28]
A lot of sites utilizing custom markup use this and it wouldn't be too bad having this for Retrospring.

Can be solved with a simple modal showing all available ways of styling text output.

**Comment by nilsding** [comment]
quick mockup 

<img width="855" alt="Screenshot 2023-01-09 at 20 33 20" src="https://user-images.githubusercontent.com/1809170/211392587-a12f69dc-0a51-461d-9366-e3d96f637d4c.png">

**Comment by nilsding** [comment]
cc @raccube

**Comment by pixeldesu** [comment]
I like the approach with the markdown icon, but I'd still like at least a small reference. Maybe on click on the icon using a [popover](https://getbootstrap.com/docs/5.3/components/popovers/)?
