### ISSUE TITLE
Remove or greatly increase the length of questions

### ISSUE THREAD

**Issue by leonoctem** [Retrospring/retrospring#311]
Currently the character limit for questions seems to be 512 characters which I feel should be greatly increased or even removed. I often find myself wanting to send creators i enjoy longer messages about their content which currently I'm unable to do on retrospring due to this word limit, and I know of others who have the same frustration with the small character limit. I know this issue has been brought up before. But I'm still seeing content creators get complaints about using retrospring due to the limit and asking them to move back to curiouscat because of it.

**Comment by pixeldesu** [comment]
We decided on a course of action for this internally.

We are leaving the general question character limit at 512, but we will give users the option to enable receiving limitless  questions, if they want to (on an opt-in basis).

The opt-in decision comes from the fact that most of the users don't ask questions above 200 characters. And after our increase from 255 to 512 characters the rate of unsent questions dropped by 85% as well.
