### ISSUE TITLE
Discussion: Give Questions the procedure to tell whether or not it was asked to a person directly or not

### ISSUE THREAD

**Issue by neptuwunium** [Retrospring/retrospring#37]
Doing this would allow us to deny answers to questions asked directly to a single person and to sort large quantity inboxes based on type, but doing so would require:
- A: A lot of processing power to process through every single record, breaking pagination

or
- B: An additional column for the question table indicating who it was asked to (user, or group)

A would require a lot of processing power for every question in a given context, looking at how many inbox entries and answers it has. The user would only be limited to the person asked if there is only one inbox or answer entry. 

B would still require that processing power when inserting the table to upgrade the existing questions to follow the new model, however thereafter we can can do all the bulk sorting within the database, saving on time and keeping pagination sane. After the migration the AJAX and API calls must and should specify the target audience column.

This is an discussion issue until we have to estimate what the impact is for both (or more) possible options and come to an agreement to which option to implement.

**Comment by pixeldesu** [comment]
We actually implemented a `direct` field for questions in #187 (+ a migration for all records before that)
