### ISSUE TITLE
Ability to hide reports with a negative score

### ISSUE THREAD

**Issue by neptuwunium** [Retrospring/retrospring#38]
This would severely clean up the moderation page.

**Comment by pixeldesu** [comment]
Actually, the thing with the moderation score probably got out of hand and turned a bit "useless" in terms what we (or I) actually planned for it.

The moderation score actually was intended to open up the ability that moderators can delete content that has enough positive votes (half of the moderators approve the report) claiming it valid. Moderators by now just have the ability to delete content straight away (I think) so this turned a bit useless, or half-implemented.

The entire system needs a rework, after all.

**Comment by pixeldesu** [comment]
Report votes are no more, so this can be closed!
