### ISSUE TITLE
Code-like text in answer box at the question page

### ISSUE THREAD

**Issue by fizzyarthur** [Retrospring/retrospring#388]
Description:
The text shown when there's nothing written in an answer box, at a question page, is `<span class="translation_missing" title="translation missing: en.views.placeholder.inbox">Inbox</span>`.

Steps to reproduce:
Go to a question page, scroll until you reach the bottom, look at the answer box.

Expected behaviour:
It should say "Write your answer here...", just like the answer boxes at the inbox page.

Testing setup:
Kubuntu 21.10
Firefox 99

Screenshot:
![Screenshot_20220425_231531](https://user-images.githubusercontent.com/96353632/165209181-c269d350-50de-421a-b8a9-04140b41f09e.png)

**Comment by nilsding** [comment]
cc @pixeldesu, looks like this was missed: https://github.com/Retrospring/retrospring/blob/c2b448ae8c30cc7d6b6d7172414ad40cd4e6126d/app/views/question/show.haml#L20

should probably be changed to `inbox.entry.placeholder`, or use a different string altogether
