### ISSUE TITLE
Two answers from a single user

### ISSUE THREAD

**Issue by fizzyarthur** [Retrospring/retrospring#391]
Description:
Somehow, I ended up answering a question twice, and each of those answers can be returned to inbox. I'm not sure if this can be reliably reproduced.

Steps to reproduce:
Answer a question from the question page, have the page freeze (probably because of network instabilities), go back (or refresh, I don't remember exactly what I did), see that the question wasn't answered, answer it again.

Expected behaviour:
A user shouldn't be able to answer a question twice.

Additional details:
Bromite 100
Android 9

Also, I remember that answering a question at the question page, going back to inbox and trying to answer it again resulted in an error message. But, this time, there were no errors reported.

Screenshots:
1. Question page after deleting the first answer
2. My inbox
3. Question page after answering with something different

![Screenshot_20220525-214259_Bromite](https://user-images.githubusercontent.com/96353632/170395366-6772b6da-7635-498c-8e19-614e3a1cb223.jpg) ![Screenshot_20220525-214252_Bromite](https://user-images.githubusercontent.com/96353632/170395387-4dbb6a4c-4313-4a80-b513-fc958cce14f1.jpg) ![Screenshot_20220525-220403_Bromite](https://user-images.githubusercontent.com/96353632/170395409-8bcff589-e4c2-4f98-868f-687e171a2470.jpg)

**Comment by raccube** [comment]
I think what's going on here is that the previous state of the inbox page is being held by Turbolinks after it loads and so it doesn't reload the page when you go back. 

Maybe there's some way to update the state kept by Turbolinks after the answer is submitted?

We should also probably throw an error when trying to answer a question you've already answered.

@pixeldesu Thoughts?

**Comment by pixeldesu** [comment]
@raccube We should handle that mostly in the backend, yes.

That should solve the issue more than messing around more with Turbolinks etc.
