### ISSUE TITLE
Switch from `@rails/ujs` to `@rails/request.js`

### ISSUE THREAD

**Issue by pixeldesu** [Retrospring/retrospring#414]
Rails UJS is/was more for the olden age of JS and jQuery, where a lot of the methods follow that methodology. [@rails/request.js](https://github.com/rails/request.js) is using `fetch()` as a base and brings most of the same features to the table.

Considering we can use both packages at the same time (probably) this can already be implemented step-by-step.

**Comment by raccube** [comment]
Done as part of #656 through to #662
