### ISSUE TITLE
why “Email can't be blank”?

### ISSUE THREAD

**Issue by Mithgol** [Retrospring/retrospring#42]
If I leave the “Email address” field blank at https://retrospring.net/sign_up the error “Email can't be blank” appears.

Consider giving users the ability of leaving that field blank. The idea is that the user cannot reset password or receive notifications in email, but the account is not compromised if the email address is ever stolen, hacked, etc.

(For example, email address is optional on the [Wikipedia's registration page](https://en.wikipedia.org/w/index.php?title=Special:UserLogin&type=signup).)

**Comment by tmprnc** [comment]
I'm not sure about this since I'm not internal to the team, but I believe it would create problems in terms of how the site works. Besides, it's also more convenient for moderation, is it not?

**Comment by pixeldesu** [comment]
The main reason why we need emails is the fact that this is one stage of preventing spambots flooding the site. With this we have validation set in between, as we also disallow the usage of throwaway emails.

Retrospring will not sell your data or use it for whatever bad behaviour people could imagine.

Another thing emails are good for are another layer of contact. If we need to contact a user specifically and they wouldn't have their Twitter connected, their website added to their profile, etc. there wouldn't be much of a way to contact the user.

**Comment by neptuwunium** [comment]
That is because Wikipedia subsitutes your email for your IP address.

**Comment by neptuwunium** [comment]
Wikipedia's "Anti-Spam" protection is actually very harsh, accounts without an email are flagged and the IP is blocked from editing pages. 

We use emails as a first catch layer of spam protection, before we started to validate emails we've encountered a number of fake accounts some of which impersonate other users. Emails do not completely prevent this but it significantly reduced the amount of garbage that has been flying in.

**Comment by Mithgol** [comment]
Ok.

**Comment by neptuwunium** [comment]
It's also to be noted that the platforms of which Retrospring and Wikipedia both stand are very different, ignoring the obvious "Social Site" vs "Encyclopedia Database", to drop emails we have to restructure some of our internal account procedures and completely rewrite chunks of the code to take in regard the nonexistence of an email.

Your concern is noted and probably will be addressed if the site ever gets fully rewritten into another structure.
