### ISSUE TITLE
you can't get to questions that are not in your inbox that only have one answer

### ISSUE THREAD

**Issue by colons** [Retrospring/retrospring#43]
it seems that there's no way to get to the detail page for questions from people you don't follow that only have one answer, even if they were asked of everyone; where most questions would have a '_n_ answers' link, if there's only one, no such link exists. even when you're looking at the person's list of questions, you can't see the answers if only one exists

**Comment by colons** [comment]
you can get to the page if you steal the `data-id` from the question element, though

that's not great on mobile

**Comment by pixeldesu** [comment]
already confirmed and reported multiple times, I just didn't get around fixing it yet (and I can't now, since I'll be absent for the next 10 days)

so someone else needs to fix the issue by then.

**Comment by colons** [comment]
oh right, sorry, i had a look at the issue list and couldn't find it

have a good break!

**Comment by pixeldesu** [comment]
I think it was reported on Retrospring and there was no issue for it yet, but it is known.
