### ISSUE TITLE
Trying to access the Sidekiq web interface sometimes signs you out

### ISSUE THREAD

**Issue by nilsding** [Retrospring/retrospring#437]
Sometimes when trying to view the Sidekiq web interface at `/sidekiq` you get greeted with a `404` instead because you get signed out for some reason.

Find out why, and fix it

**Comment by nilsding** [comment]
Looks like Sidekiq::Web uses a different session cookie (`rack.session`) than the Rails one (`_justask_session`), maybe that's why?

**Comment by nilsding** [comment]
I think we should get Sidekiq up to date first, maybe that already resolves it.

**Comment by pixeldesu** [comment]
Ever since that one PR with the Devise route constraint and afterwards the Sidekiq updates, I was not logged out of Retrospring visiting the page. Did it occur for you again recently?

**Comment by nilsding** [comment]
just tried it, and nope, still happens to me.

**Comment by pixeldesu** [comment]
@nilsding can you recheck this every now and then? I've been messing around with this in the past few days and I wasn't logged out once so far.

**Comment by raccube** [comment]
Seems to no longer happen for me.

**Comment by nilsding** [comment]
might have been resolved with the upgrade to sidekiq 6 in 18a150b969a5a8e92167af8c53b4d48d5dcda4e8

closing for now
