### ISSUE TITLE
Theming Bugs

### ISSUE THREAD

**Issue by neptuwunium** [Retrospring/retrospring#46]
List of theming bugs yet to be addressed
- [x] The stats page on a user's profile (`.entry-subtext`)
- [ ] Search icon?
- [x] Dark and Light presets are too monotone (modify `primary` and `warning` and `link color`)
- [ ] API methods (`GET/PATCH /api/sleipnir/user/theme`)
- [x] Navigation current tab
- [x] Notifications get a 1px top-border when hovering
- [x] Dropdown chevron
- [x] Turbolinks doesn't respect page transitions 
- [x] Wipe Theme button (`GET /settings/theme/destroy`)
- [x] Certain links have incorrect colors
- [x] Notifications Badge reverts to purple when activated
- [x] Outline color
- [x] Headings
- [x] Panels aren't themed in accordance to the different color types (`primary`, `warning` etc)

insight:
- [x] Selection color
- [x] Input color

also: 
- [x] Implement system to retroactively regenerate every single theme once the source is modified. (Rake, or at startup)

**Comment by neptuwunium** [comment]
Amend: API Methods

**Comment by pixeldesu** [comment]
can you apply `darken` to colors with the current setup? `.entry-subtext` would need that if it uses the primary color.

**Comment by neptuwunium** [comment]
probably

**Comment by neptuwunium** [comment]
amend: navigation current tab

**Comment by neptuwunium** [comment]
amend: notification border

**Comment by neptuwunium** [comment]
amend: dropdown chevron isn't colored

**Comment by pixeldesu** [comment]
If you are on a profile and visit another one, the theme carries over.

I guess Turbolinks is causing the issue here.

**Comment by neptuwunium** [comment]
fucking
turbolinks

**Comment by pixeldesu** [comment]
Also, as mentioned in the Slack, some sort of sharing code wouldn't be too bad.

It could be made so simple that it is just onsite Javascript combining all inputs together and replacing them if you paste something in.

**Comment by neptuwunium** [comment]
it's possible, everything is just a number in the system anyway, and you know my love for bitwise operations

**Comment by neptuwunium** [comment]
amend: 
 Certain links have incorrect colors
 Notifications Badge reverts to purple when activated
 Outline color
 Headings
 Selection color
 Input color

**Comment by neptuwunium** [comment]
amend: panels aren't themed in accordance to the different color types

**Comment by pixeldesu** [comment]
Theming was completely replaced with #68 so this is invalid now.
