### ISSUE TITLE
a way to export all of your data

### ISSUE THREAD

**Issue by tinruufu** [Retrospring/retrospring#47]
i would like this very much, even if it's just like a json dump of all of your questions and answers and comments

**Comment by pixeldesu** [comment]
We have a manual task to export user data in a .json file already, I guess there would be no problem to move it into a feature on the site, but we'd need to move the export generation into a worker so it won't timeout/affect the site in any way, marking this off as low priority now.

**Comment by nilsding** [comment]
Already implemented a few years back.
