### ISSUE TITLE
Can't delete account

### ISSUE THREAD

**Issue by serra111** [Retrospring/retrospring#516]
Every time I try to delete my account, I receive the 500 Internal Server Error page. I've tried to do it from both the mobile web app and on my computer. Any way this can be fixed? 

(Also, just want to say I don't have any issue with the website itself; it's great and serves it's purpose, but I'm being harassed by a very determined person across multiple platforms, so I'm trying to limit the ways they can try to communicate with me in hopes that they eventually get bored. Keep up the good work!)

**Comment by raccube** [comment]
The fix for this has been deployed. Please comment here if you have any further issues.
