### ISSUE TITLE
Code-like text in certain comment notifications

### ISSUE THREAD

**Issue by fizzyarthur** [Retrospring/retrospring#520]
Description:
When I receive a notification from a comment that another person made to someone else's answer, there's code gibberish at the notification title.

Steps to reproduce:
Have person A answer your question. Have person B comment on that answer. Check your notifications and voilà.

Expected behaviour:
The title should display something like "Person B commented on person A's answer"

Testing setup:
Firefox 102

Screenshots:
![retrobug](https://user-images.githubusercontent.com/96353632/179142724-47af3bd9-4766-4ab6-bc91-c28ba1402247.png)

![retrobug2](https://user-images.githubusercontent.com/96353632/179142763-8cd641b2-1d73-45c8-aaf7-5b146a7f1fa7.png)

**Comment by raccube** [comment]
[Related view](https://github.com/Retrospring/retrospring/blob/main/app/views/notifications/type/_comment.haml#L7-L21)
