### ISSUE TITLE
truncated tweets should never be shorter than 140 characters

### ISSUE THREAD

**Issue by tinruufu** [Retrospring/retrospring#53]
the way truncation works at the moment is [pretty basic](https://github.com/Retrospring/retrospring/blob/e39da499ce0888d36c170253bd61747d1d3dbb01/app/models/services/twitter.rb#L30), and it leads to stuff like [this](https://twitter.com/tinruufu/status/652188722046308353) happening, which makes me sad

an initial check to see if an untruncated tweet would work would help massively, but that'd only solve 'if it is possible to fit an entire question and answer in a tweet, that should happen'; even [when truncation is necessary](https://twitter.com/tinruufu/status/652075786820845568), as much content as possible should be included in the tweet. how much to truncate from the question vs the answer is a potentially complicated problem, though

if someone is in this logic anyway, it'd probably be prudent to respect `short_url_length` from https://dev.twitter.com/rest/reference/get/help/configuration

**Comment by neptuwunium** [comment]
N.B. 

``` ruby
def create_twitter_message(answer, question, short_url_length_https = 23, separator = 'ー', dots = '…')
  q = render_markdown(question.content).gsub(/\@(\w+)/, '\1')
  a = render_markdown(answer.content)

  l = 140 - separator.length - short_url_length_https - 1

  if q.length + a.length > l
    lQ = (l / 2).floor
    lA = (l / 2).ceil
    if q.length > lQ
      q = q[0...lQ - dots.length] + dots
    end

    if a.length > lA
      a = a[0...lA - dots.length] + dots
    end
  end

  a_url = show_user_answer_url(
    id:       answer.id,
    username: answer.user.screen_name,
    host:     APP_CONFIG['hostname'],
    protocol: (APP_CONFIG['https'] ? :https : :http)
  )

  "#{q}#{separator}#{a} #{a_url}"
end
```

**Comment by tinruufu** [comment]
👌💯

**Comment by pixeldesu** [comment]
Dropping this issue in favor of #99 because text shortening is kinda busted in general, not just for social media/Twitter posts!
