### ISSUE TITLE
the front page pitch is almost impossible to read on desktop safari

### ISSUE THREAD

**Issue by tinruufu** [Retrospring/retrospring#54]
![safari text](https://cloud.githubusercontent.com/assets/13986685/10417819/cb0edaf4-7040-11e5-9d0b-1085539e1ecd.png)

also looks like that in the latest webkit nightly

**Comment by raccube** [comment]
![image](https://user-images.githubusercontent.com/6197148/79795151-63e59e80-834b-11ea-9880-8d44b91ccf87.png)
Safari 13.1 on Catalina.

Guess this is no longer relevant
