### ISSUE TITLE
Add option to disable search indexing for a user

### ISSUE THREAD

**Issue by pixeldesu** [Retrospring/retrospring#542]
If toggled, it should add a `<meta name="robots" content="noindex, nofollow"/>` to the `<head>` of a users profile and answers.

This implementation can (and should) be generalized so we can toggle this state for other pages, so there's a global/something else in the main layout to check for this.

**Comment by nilsding** [comment]
/me is not a SE"O" expert, so...

will something like that be required for links to user profiles/answers too?
