### ISSUE TITLE
Auto foxus text field in ask modal

### ISSUE THREAD

**Issue by raccube** [Retrospring/retrospring#557]

**Comment by raccube** [comment]
@nilsding 
![](https://user-images.githubusercontent.com/1809170/178102715-b3b4c053-2a38-4001-908d-b9e747769fb1.jpg)

**Comment by nilsding** [comment]
@raccube 
![image](https://user-images.githubusercontent.com/1809170/180605813-48aa3623-24b7-41ce-8bac-90f33515cf37.png)

**Comment by raccube** [comment]
This is why we don't get any contributors.

**Comment by nilsding** [comment]
to any potential future contributors: this is just us having fun, we're literally sitting right next to each other ;-) 

we'll be more serious.  i promise!
