### ISSUE TITLE
CSS breaks when name is too long. (user_controller@friends)

### ISSUE THREAD

**Issue by jeyemwey** [Retrospring/retrospring#56]
You see what I mean. Maybe, you have to longer the panels to prevent this.

![unbenannt](https://cloud.githubusercontent.com/assets/2796271/11484527/c7a9e512-97ae-11e5-9e78-f97d03d2c81b.png)

(Source: https://retrospring.net/Revengeday/friends)

And.. @SirDisi, it's all about you!

**Comment by pixeldesu** [comment]
This is fixed in the new theme introduced with #68
