### ISSUE TITLE
Add notice that account deletion is permanent

### ISSUE THREAD

**Issue by pixeldesu** [Retrospring/retrospring#581]
Too many people think that account deletion on Retrospring follows the same scheme of services that either never delete your data, or delete it only after a month.

Currently account deletion is a red button with an additional confirmation, looks like we'll have to add more disclaimer text (and more red) to that section.

**Comment by raccube** [comment]
This was partly done in [#591](https://github.com/Retrospring/retrospring/pull/591/files#diff-2a0850f41dc575b8e91a594eb645f9aad754fddc42a9c1ea8fcc932b399b00cdR273-R274)

**Comment by pixeldesu** [comment]
I think this in fact is enough, if people don't read a warning that says the action is **IRREVERSIBLE** (in that casing), then a box with red text isn't going to be read any more than that.
