### ISSUE TITLE
Show sent anonymous questions for moderators

### ISSUE THREAD

**Issue by raccube** [Retrospring/retrospring#612]
We currently hide anonymous questions from user profiles. For moderation purposes, it would be good to be able to view anonymous questions which a user has sent. Optionally with a filter for the recipient.

**Comment by pixeldesu** [comment]
We should simply change the type of posts we fetch in the backend if the unmasking mode is enabled so that it reflects the "old" behaviour again.

**Comment by raccube** [comment]
Resolved with #630
