### ISSUE TITLE
Load more button on profile pages is cut off when opened as a PWA on iOS

### ISSUE THREAD

**Issue by raccube** [Retrospring/retrospring#641]
![image](https://user-images.githubusercontent.com/6197148/186112703-419a78e9-691a-43e1-a465-7eff2ee58697.jpeg)

**Comment by pixeldesu** [comment]
This actually isn't the case anymore with the new centered layout and us including the footer on all pages again.

**Comment by raccube** [comment]
The links still get cut off. 
![image](https://user-images.githubusercontent.com/6197148/203157445-6a636936-d2e5-47bf-90b6-82cf81ea9b47.png)
