### ISSUE TITLE
Mastodon/Fediverse sharing

### ISSUE THREAD

**Issue by raccube** [Retrospring/retrospring#79]
Add an option to share to Mastodon/Pleroma/∞ in the same manner as how Twitter sharing currently works.

- [ ] Must be able to attach an account to post to as a service
- [ ] Must be able to control the post's privacy level (default = followers only)
- [ ] Must be able to set a content warning (default = retrospring answer)
- [ ] Must be able to publish answers to Mastodon

**Comment by LunarLambda** [comment]
Would love that!

**Comment by raccube** [comment]
Updated the description with a list of requirements.

**Comment by pixeldesu** [comment]
This already is a bit old, but maybe we can work with this:
https://github.com/mastodon/omniauth-mastodon

**Comment by DrSkyfaR** [comment]
Hello all,
is there by any chance after 2 years an update on the sharing of questions about Mastodon ? Hello after two Years,

**Comment by pixeldesu** [comment]
Considering we are now in the planning stages of how to implement ActivityPub, I am going to close this issue. Sharing via connected accounts won't be necessary if you can just follow an account in the fediverse directly!
