### ISSUE TITLE
Implement Captcha for Registration

### ISSUE THREAD

**Issue by pixeldesu** [Retrospring/retrospring#89]
We're getting slightly bombarded with spam user registration, basically since sometime around 2018.

To combat that, we should consider adding a captcha-solution to the registration process.

**Possible solutions:**
* [Google ReCaptcha](https://www.google.com/recaptcha/intro/v3.html), which we would like to avoid, because of Google
* [hCaptcha](https://www.hcaptcha.com/), which Cloudflare has switched to, dropping ReCaptcha.

**Comment by nilsding** [comment]
-1 on recaptcha for obvious reasons.

hCaptcha looks interesting though.
