### ISSUE TITLE
Add a form on the site for feedback/feature requests/bug reports.

### ISSUE THREAD

**Issue by raccube** [Retrospring/retrospring#90]
Currently the only way to submit any feedback for Retrospring is to create an issue in this issue tracker. This requires the user to have a GitHub account, likely deterring users from submitting their feedback or suggestions.

We have a few options for how we could tackle this:

- Creating a form which simply opens a GitHub issue (could use @Kaisrrerr for this)
- The above but with some kind of admin approval before opening an issue on GitHub
- Repurposing the current moderation system to create a "Feedback Hub" of sorts where users can vote on issues

**Comment by pixeldesu** [comment]
We thought about setting up [Fider](https://getfider.com/) for that as well.

**Comment by pixeldesu** [comment]
I got into contact with [Canny](https://canny.io/) after I saw them being used on another site and offering an OSS program, and in case they accept us, I'll also go forward with implementing it into the website.
