### ISSUE TITLE
separate colours for card tops/bottoms

### ISSUE THREAD

**Issue by nilsding** [Retrospring/retrospring#944]
felt like making a NeXTStep-like theme, but I can't fully pull it off yet.

## current state

the card appendages ("raised content") only allow for a single background colour, and re-use the body text colour.

so my current theme looks like that:

<img width="861" alt="Screenshot 2023-01-09 at 20 25 45" src="https://user-images.githubusercontent.com/1809170/211391127-3cce4924-1ad3-40f6-86a5-1c0c95a2b1e0.png">

## desired state

first of all, separate text colours for the raised content -- if I want to make the background black it'll be unreadable as the body text colour is black too.

second, have an option to change the tops and bottoms separately if i desire to.  by default that option would be disabled and change the colours for both. 

this would let me change the theme to something like that, making answers look more like NeXTStep windows: 

<img width="876" alt="Screenshot 2023-01-09 at 20 23 36" src="https://user-images.githubusercontent.com/1809170/211390741-2b318a16-2027-468d-8531-ce2f6e8519f4.png">

**Comment by pixeldesu** [comment]
> first of all, separate text colours for the raised content -- if I want to make the background black it'll be unreadable as the body text colour is black too.

That's what I can offer to implement, but a (conditional) top section might be harder to implement.
