### ISSUE TITLE
Serve webfont ourselves

### ISSUE THREAD

**Issue by nilsding** [Retrospring/retrospring#95]
Just to not forget about it when we start moving everything to Webpacker...

[Right now](https://github.com/Retrospring/retrospring/blob/1d7430c3f786f42bb5e416eb4596f426d57a19a9/app/assets/stylesheets/application.css.scss#L11) the Lato webfont is served by E-Corp.  We really should host this ourselves.

**Comment by raccube** [comment]
Alternatively we could drop Lato entirely and use something like `font-family: system-ui, -apple-system, BlinkMacSystemFont, "Segoe UI", Ubuntu, Cantarell, Oxygen, Roboto, "Helvetica Neue", sans-serif;`

...or use something else entirely
