### ISSUE TITLE
Scrolling the notification dropdown causes layout issues on mobile

### ISSUE THREAD

**Issue by raccube** [Retrospring/retrospring#956]
https://user-images.githubusercontent.com/6197148/212503516-6b6a7b8b-654e-43bc-a996-e9310f765bca.MOV

**Comment by pixeldesu** [comment]
Can't we just remove the dropdown on mobile?

Case in point: considering that it is full-height now it doesn't actually matter if we open the notifications page, it's less buggy that way and through Turbo the navigation back should be quite fast anyway.
