### ISSUE TITLE
Notification texts are cut off on notification page

### ISSUE THREAD

**Issue by pixeldesu** [Retrospring/retrospring#96]
Reported here: https://retrospring.net/xvilyv/a/169642

I'm not even sure if that was a thing before or not, but probably a good idea to show full texts on the notification list if possible. It should only be shortened in the notification dropdown.

**Comment by raccube** [comment]
The notifications and user dropdowns are also cut off.
![image](https://user-images.githubusercontent.com/6197148/81472957-56f1f780-91f3-11ea-8d27-409221bdefd0.png)


[Reported here](https://retrospring.net/arman/a/169750)
