### ISSUE TITLE
Make validation errors for usernames descriptive

### ISSUE THREAD

**Issue by pixeldesu** [Retrospring/retrospring#975]
"`username` is invalid" is not really helpful, the error should state what exactly is not correct when validating (format, length, etc.)

**Comment by nilsding** [comment]
seems easy enough to do, just add the `:message` option to the `:format` hash in the validation:

- https://guides.rubyonrails.org/active_record_validations.html#message
- https://github.com/Retrospring/retrospring/blob/16bba0b7f0e87b5414adea13f138efd231ef91aa/app/models/user.rb#L64

**Comment by pixeldesu** [comment]
Additionally, the length check should be moved out of the `SCREEN_NAME_REGEX` so it can get its own message as well.
