### ISSUE TITLE
How is email sending configured?

### ISSUE THREAD

**Issue by ioistired** [Retrospring/retrospring#999]
Ok, I have a running instance now, but I don't see how to configure the SMTP server etc to use. So far I have received no email after signing up. How is this configured?

**Comment by nilsding** [comment]
https://guides.rubyonrails.org/action_mailer_basics.html#action-mailer-configuration

**Comment by ioistired** [comment]
Does this go in config/justask.yml?

**Comment by nilsding** [comment]
no.  as the example config below it says

> An example would be adding the following to your appropriate `config/environments/$RAILS_ENV.rb` file

**Comment by ioistired** [comment]
OK, it seems kind of weird to put configs in a file tracked in git but I will put it there.

**Comment by pixeldesu** [comment]
Configuration isn't perfect still, there's #100 to improve on that.
